[project]
name = "advent_of_code_2024"
version = "0.0.1"
authors = [
  { name="Holger Janßen-Kroll" },
]
description = ""
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]

